[0m[[0m[31merror[0m] [0m[0mjava.net.ConnectException: Connection refused[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.Net.connect0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.Net.connect(Net.java:579)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.Net.connect(Net.java:568)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.Socket.connect(Socket.java:633)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.Socket.connect(Socket.java:583)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:929)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)[0m
[0m[[0m[31merror[0m] [0m[0m	at solution$.sendHttpPostRequest(solution.scala:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at solution$.main(solution.scala:424)[0m
[0m[[0m[31merror[0m] [0m[0m	at solution.main(solution.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:568)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1986)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1925)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:833)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) java.net.ConnectException: Connection refused[0m
